v4-client-py/pyproject.toml, v4-client-py/v4_client_py/clients/composer.py
This is a quick hack to get MM testnet onboarding unblocked. This should be fine since the Python client is not used by the frontend, and therefore doesn't send stateful order cancellations.
[Slack thread for context](https://dydx-team.slack.com/archives/C05S4CTSQ74/p1695218524347379?thread_ts=1695071666.623229&cid=C05S4CTSQ74).
=> [PY] v0.6.6 only cancel Short-Term orders, break stateful order cancellations

v4-client-js/examples/composite_example.ts, v4-client-js/examples/human_readable_short_term_orders.json, v4-client-js/examples/short_term_composite_example.ts, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/constants.ts
Equivalent of #32  for TS. LMK If I missed anything.
=> [TS] [CLOB-895] short term place orders for TS

v4-client-js/examples/native_examples.ts, v4-client-js/examples/transfer_example_send.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/constants.ts, v4-client-js/src/clients/modules/composer.ts, v4-client-js/src/clients/modules/post.ts, v4-client-js/src/clients/native.ts, v4-client-js/src/clients/types.ts, v4-client-js/src/network_optimizer.ts
Also validatorClient allow token decimals to be configurable
=> Send message to ingest amount as string

v4-client-js/__tests__/modules/client/Transfers.test.ts, v4-client-js/__tests__/modules/client/ValidatorPostEndpoints.test.ts, v4-client-js/examples/composite_example.ts, v4-client-js/examples/long_term_order_cancel_example.ts, v4-client-js/examples/short_term_order_cancel_example.ts, v4-client-js/examples/short_term_order_composite_example.ts, v4-client-js/examples/test.ts, v4-client-js/examples/transfer_example_deposit.ts, v4-client-js/examples/transfer_example_send.ts, v4-client-js/examples/transfer_example_subaccount_transfer.ts, v4-client-js/examples/transfer_example_withdraw.ts, v4-client-js/examples/transfer_example_withdraw_other.ts, v4-client-js/examples/validator_post_example.ts, v4-client-js/package-lock.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/modules/post.ts, v4-client-js/src/clients/native.ts, v4-client-js/src/clients/subaccount.ts, v4-client-js/src/index.ts
There's one Subaccount already in proto generated types. That is the type that is returned when we query the chain.
```
import { Subaccount } from '@dydxprotocol/v4-client-js/build/src/clients/modules/proto-includes';
import { Subaccount as SubaccountClient } from '@dydxprotocol/v4-client-js/build/src/clients/subaccount';
```
This new `SubaccountInfo` is used to represent Subaccount tuples of (wallet, subaccountNumber) in our clients.
Bumped 1.0.0 to 1.0.1
=> Rename Subaccount to SubaccountInfo

v4-client-js/examples/noble_example.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/local-wallet.ts, v4-client-js/src/clients/native.ts, v4-client-js/src/clients/noble-client.ts, v4-client-js/src/lib/constants.ts
Run `v4-client-js/examples/noble_example.ts` to test ibc transfers between dydx and noble testnets.
=> Create NobleClient for interacting with noble

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/scripts/generate-cctp-protos.sh, v4-client-js/src/clients/lib/cctpProto.ts, v4-client-js/src/clients/native.ts, v4-client-js/src/clients/noble-client.ts
Created `v4-client-js/scripts/generate-cctp-protos.sh` for generating the noble proto needed for `/circle.cctp.v1.MsgDepositForBurn`, only one of the proto file is needed. it can be updated with `npm run update-cctp-protos`
=> Support CCTP withdraw and noble proto for MsgDepositForBurn

v4-client-js/src/clients/native.ts
Otherwise, it doesn't return the proper response back to the caller.
=> Skip noble validator connection errors

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/get.ts, v4-client-js/src/clients/modules/proto-includes.ts
Add two new methods to `ValidatorClient`
- `getWithdrawalAndTransferGatingStatus`
- `getWithdrawalCapacityByDenom`
bump `v4-protos-js@4.0.0-dev.0`
codegen `v4-native-client`
Tested locally with the resulting responses:
=> v1.0.18: Add Withdraw Gating/Capacity query methods

v4-client-js/examples/noble_example.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/constants.ts, v4-client-js/src/clients/modules/post.ts, v4-client-js/src/clients/native.ts, v4-client-js/src/clients/noble-client.ts, v4-client-js/src/clients/validator-client.ts
Having Memos for our transactions is useful for research on-chain analysis to track which transactions are made by are front-end.
=> Allow clients to set a default memo to for transactions

v4-client-js/examples/gov_add_new_market.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/modules/composer.ts
JS numbers that are too large result in scientific notation. In this specific case, `1e22` which could not be parsed when composing a governance proposal.
Changed expected type from `number` -> `string`
=> v1.0.19: Update expected type for Initial deposit amount

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/post.ts
same logic as MsgPlaceOrder, broadcast mode should be `Method.BroadcastTxCommit` for long term order cancels, so that FE can properly wait for order cancel to commit before sending another cancel order tx
=> default broadcast mode for MsgCancelOrder

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/native.ts
[MOB-298 : support custom txn memo field parameter for native libs](https://linear.app/dydx/issue/MOB-298/support-custom-txn-memo-field-parameter-for-native-libs)
in order to differentiate iOS and Android txns in the memo, the memo description must be configurable for clients
=> MOB-298 : support custom txn memo field parameter for native libs

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/post.ts
conditional orders also require sequence numbers (all stateful use seq numbers) -- therefore should wait before previous tx to commit before submitting a new one, similar to long term orders
=> add default broadcast mode for conditional orders

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/native.ts
Correct a mistake in a [previous PR](https://github.com/dydxprotocol/v4-clients/pull/126).  Abacus is expecting the status code as well, so we need to pass it over.
=> Send status to the native faucet call

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/native.ts
[MOB-2 : iOS: Update dydxClient hook to support query for withdrawal gating](https://linear.app/dydx/issue/MOB-2/ios-update-dydxclient-hook-to-support-query-for-withdrawal-gating)
- adds native wrappers for the `GetWithdrawalAndTransferGatingStatus ` and `getWithdrawalCapacityByDenom` methods
=> MOB-2 : iOS: Update dydxClient hook to support query for withdrawal gating

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/account.ts
The client is trying to go to `/v4/orders${orderId}` and is missing the `/` that is required between `orders` and `${orderId}`.
=> Fix get order api request

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/native.ts
If defaultDydxGasPrice is not supplied, validatorClient will use defaultGasPrice (USDC), which could cause the transaction to fail.
=> Mobile: Passing defaultDydxGasPrice for DYDX token transfer

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts
when submitting a governance proposal for `DYDX-USD`
1. do not create a new oracle market (as there's an existing one)
2. point perpetual to existing market with ID `1000001`
=> point perpetual at existing market when submitting dydx-usd proposal

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/constants.ts, v4-client-js/src/clients/faucet-client.ts, v4-client-js/src/clients/modules/post.ts, v4-client-js/src/clients/validator-client.ts
- Expose setters to select different denom `gasPrice` for transactions within the Validator Client.
- Add native token faucet to FaucetClient
=> v1.1.10: Gas denom selection

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/subaccount.ts, v4-client-js/src/lib/constants.ts
- Fix `transferToSubaccount` by removing zeroFee flag
- Update validation to account for new `MAX_NUMBER_SUBACCOUNTS`
=> v1.1.11: Remove zeroFee for subaccount transfer, update MAX_NUMBER_SUBACCOUNTS

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/constants.ts
was hitting `Unregistered type url: /cosmos.staking.v1beta1.MsgWithdrawDelegatorReward` in web, realized it was in `distribution` from doc [here](https://docs.rs/juno-rust-proto/latest/juno_rust_proto/cosmos/distribution/v1beta1/struct.MsgWithdrawDelegatorReward.html)
=> fix url for withdrawing delegator rewards

v4-client-js/__tests__/modules/client/AccountEndpoints.test.ts, v4-client-js/src/clients/modules/account.ts
This PR exposes two endpoints for fills and transfers related to the `v4/fills/parentSubaccountNumber` route
=> feat: add parent subaccount queries

v4-client-js/__tests__/lib/helpers.test.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/helpers/chain-helpers.ts
there was a javascript/typescript precision error with the exponentiation causing some trade input values to be rounded incorrectly (notably if you try to input 8.45 on the TIA market, you'll always get back a trade at 8.44). Resolved by using BigNumber library. Tested by verifying new test fails before changes; passes after changes. (Test mock data is equivalent to inputs from the TIA market)
=> fix: fix rounding error on certain values in calculateSubticks

v4-client-js/__tests__/modules/client/MarketsEndpoints.test.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/markets.ts
Adds the `createdBeforeOrAt` param to the JS client's GetTrades function.
=> Adding createdBeforeOrAt param to getTrades API

v4-client-js/examples/websocket_example.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/socket-client.ts
- Adding onError callback allows users to handle errors.
- readyState helper functions allow users to determine the current state of the underlying websocket.
=> Add onError callback to socket client and readyState helpers

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/noble-client.ts
adds `'/circle.cctp.v1.MsgDepositForBurnWithCaller'` so we can use skip's smart relay functionality
=> feat: register msgDepositForBurnWithCaller type

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/noble-client.ts
set correct gas price for noble. it should be 0.1uusdc and not 0.025uusdc.
resolves linear ticket OTE-565 fix smart relay https://linear.app/dydx/issue/OTE-565/[client-js]-fix-smart-relay
=> fix: correct gas price for noble [OTE-565]

v4-client-js/.gitignore, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/tsconfig.json
[to enable local installation of v4-clients](https://linear.app/dydx/issue/OTE-570/[v4-web]-install-local-client-js), we need to make sure our vite config ignores node modules. this will allow us to develop on v4-clients while experiencing the effects on v4-web directly
=> fix: enable local builds for OTE-570

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/native.ts
Otherwise, the abacus call from mobile would fail.
=> Fix incorrect native function name in getCurrentUnstaking

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/native.ts
It's not being used by mobile (since there is no staking on mobile yet), but we will need this to test the Abacus refactor.
=> Add getDelegationTotalRewards call for mobile

v4-client-js/__tests__/modules/client/AccountEndpoints.test.ts, v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/modules/account.ts
The function was originally using param names like effectiveBeforeOrAt but param names are expected to be createdBeforeOrAt and createdOnOrAfter instead. Also, the function was missing the block height versions of the createdBeforeOrAt and createdOnOrAfter query params, so I added those in too.
=> Fix the historical pnls indexer query

v4-client-js/package.json
change v4-proto to be a peer dep so we can tell if versions are mismatched
=> chore: change v4-proto to peer dep

v4-client-js/README.md, v4-client-js/__tests__/lib/helpers.test.ts, v4-client-js/src/clients/helpers/chain-helpers.ts
by using BigNumber, instead of hitting precision errors with Javascript.
Test case added reflects the 0.0003 size on BTC that used to round to 0.0002; verified that the test fails before the change and passes after the change.
=> fix: fix rounding error on order sizes

v4-client-js/package.json
Was running into an issue where everytime I tried to commit with an updated v4-clients, I got 
```Cannot find module '@dydxprotocol/v4-proto/...``` 
Figured out from [here](https://dev.to/jody/a-tip-on-using-peer-dependencies-with-typescript-2bji) that this is expected from moving proto into peerDependencies. Managed to get things working (using jeremy's nifty lil local install script) by duplicating into `devDependencies` which I think should be adequate (as opposed to moving it into `dependencies` but someone lmk if I'm wrong
=> fix: duplicate v4-proto dep into devDep

.github/workflows/js-publish.yml, v4-client-js/.npmignore, v4-client-js/package-lock.json
semantic-release is smart enough to know to **not** pack any node modules, so we have to purposefully override via `.npmignore` 
However, i accidentally created.... version 3.16. We'll need @BrendanChou to remove it https://www.npmjs.com/package/@dydxprotocol/v4-client-js?activeTab=versions (sorry 🙇 )
=> fix: package node modules

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/modules/post.ts, v4-client-js/src/clients/validator-client.ts
motivation:
- in FE, when creating the first transaction (e.g. placing a short term order after web app starts), we need to query account as part of the tx to get the account number before sending the place order message.
- we can actually pre populate the account number cache earlier (i.e. app starts / clients initialized with address) so it doesn't have to be a blocker
- once timestamp nonce is enabled, we will no longer need to fetch account seq number, so this will also help eliminate the round trip time blocker when placing a stateful order first
change:
- add `populateAccountNumberCache` function
testing:
- tested locally / integration with FE app https://github.com/dydxprotocol/v4-web/pull/1062
- backwards compatible
=> feat: add function to prepopulate account number cache

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/constants.ts, v4-client-js/src/clients/modules/post.ts, v4-client-js/src/clients/validator-client.ts
- account sequence number can soon be replaced by timestamp
- this eliminates the need to to fetch account sequence number from account as part of tx options
- adding a flag / config param since this isn't completely out yet
testing:
- tested locally / breakpoints that transactions work, and no unnecessary fetch to account for placing stateful orders
=> feat: support for timestamp nonce

v4-client-js/package-lock.json, v4-client-js/package.json, v4-client-js/src/clients/helpers/request-helpers.ts, v4-client-js/src/clients/native.ts
…client.
The vault responses contain Uint8Array that needs to be converted back to bigint.
=> feat: copy the v4-web parseToPrimitives utility here for the mobile native

v4-client-rs/client/Cargo.toml
Fix README file path in Rust client's Cargo.toml.
=> chore: Fix Rust client Cargo.toml README path

v4-client-rs/client/Cargo.toml
Fixes GitHub link pointing to the package source. Affects the link shown in the crates.io page.
=> chore: Fix Rust client Cargo.toml repository link

v4-client-js/examples/websocket_orderbook_example.ts
when i use a WebSocket to get the price, there was no properly documented example so i made it.
For information on resolving the cross order book, i saw dydx docs (https://docs.dydx.exchange/api_integration-guides/how_to_uncross_orderbook)
+ i reflected feedback
=> feat: add crossed orderbook resolving example using websocket

v4-client-js/__tests__/clients/composite-client.test.ts, v4-client-js/examples/permissioned_keys_example.ts, v4-client-js/package-lock.json, v4-client-js/src/clients/composite-client.ts, v4-client-js/src/clients/constants.ts
Authenticators can be easily misused. This code adds an `validateAuthenticator` function that does some rudimentary checks to ensure that users are adding a signatureVerification authenticator as part of any combination of authenticators that are added.
=> feat: Add functionality to validate authenticators added my clients

v4-client-js/src/clients/modules/account.ts
Reference to the PR this one is created in place of [here](https://github.com/dydxprotocol/v4-clients/pull/389)
=> fix: url mapping of getParentSubaccount
